version: '3'
services:
  db:
    image: mysql:5.7
    env_file:
      - ./.my.env
    ports:
      - "4306:3306"
    volumes:
      - ./db/mysql/volumes:/var/lib/mysql

  web:
    tty: true
    stdin_open: true
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/time-viewer
    ports:
      - "3000:3000"
    env_file:
      - ./.my.env
    links:
      - db
